#!/bin/bash
for d in $(find -type d -name ".git"); do
    ( cd $d/.. && pwd && git checkout -f $1 && git reset --hard origin/$1 && git pull)
done
find . -name *.pyc -delete && find . -type d -empty -delete